app:
  kind: production
  domain: localhost
  port: 8088

db:
  mongo:
    username: root
    password: root
    host: localhost
    port: 27017
    name: stock_trade
    auth: admin
    collection: trades
  mariaDB:
    username: hadi
    password: "2050571"
    host: localhost
    port: 3306
    name: stock_trade
