app:
  kind: production
  domain: localhost
  port: 8088

db:
  mongo:
    username: root
    password: root
    host: localhost
    port: 27017
    name: stock_trade
    auth: admin
    collection: trades
  mariaDB:
    username: root
    password: ZkHRUiDs5xnW
    host: 88.135.39.149
    port: 7854
    name: hadimasu_db
