app:
  kind: staging
  domain: localhost
  port: 8087

db:
  mongo:
    username: root
    password: root
    host: localhost
    port: 27017
    name: stock_trade
    auth: admin
    collection: trades
